# Deep Neural Network

![test](https://github.com/pydsmldlmeetup/DeepLearning/blob/master/data/image_001_deep_neural_network.PNG?raw=true)

### network architecture
・first layer = input layer (2 nodes)<br>
・second layer = hidden layer (3 nodes)<br>
・third layer = hidden layer (3 nodes)<br>
・last layer = output layer (1 nodes)<br>

In [13]:
import numpy as np

# create input data X
X = np.random.random((2, 1))

# initialize w (weight) 
w1 = np.random.random((2, 3))
w2 = np.random.random((3, 3))
w3 = np.random.random(3)

print("---- w1 ----")
print(w1)
print("\n---- w2 ----")
print(w2)
print("\n---- w3 ----")
print(w3)


---- w1 ----
[[0.38491364 0.67798837 0.39503721]
 [0.44112948 0.49428774 0.51738987]]

---- w2 ----
[[0.34741111 0.36190585 0.990897  ]
 [0.6385628  0.94188125 0.65343182]
 [0.20093324 0.27013368 0.66401873]]

---- w3 ----
[0.38060347 0.25590247 0.39767622]


In [17]:
h1 = X * w1
h1 = np.sum(h1, axis=0)
print(h1)

[0.68678517 0.98706129 0.75576738]


In [20]:
h2 = h1 * w2
h2 = np.sum(h2, axis=0)
print(h2)

[0.81515023 1.55355628 1.74457376]


In [24]:
y = h2 * w3
y = np.sum(y)
print(y)

1.401583388441413
